### ISSUE TITLE
Application can't start

### ISSUE THREAD

**Issue by Vovkiv** [Bytezz/IPLookup-gtk#20]
After lastest 0.3.0 update, application can't start anymore.
Running it in terminal gives this traceback:
```
Error building template class 'IplookupWindow' for an instance of type 'IplookupWindow': .:0:0 Invalid object type AdwToolbarView'
Traceback (most recent call last):
  File "/app/share/iplookup/iplookup/main.py", line 49, in do_activate
    self.win = IplookupWindow(application=self)
  File "/app/share/iplookup/iplookup/window.py", line 49, in __init__
    self.ip_entry.grab_focus()
AttributeError: 'NoneType' object has no attribute 'grab_focus'
```

In some cases it will start, but will look like this:

![image](https://github.com/Bytezz/IPLookup-gtk/assets/54743395/3c7c911c-5261-47dc-b22b-9fa54a5b356e)

**Comment by Bytezz** [comment]
Sorry for the late reply, I just got back from vacation.
Thank you @TheEvilSkeleton for fixing this before my return.
