### ISSUE TITLE
Better appstream screenshots

### ISSUE THREAD

**Issue by bertob** [Bytezz/IPLookup-gtk#26]
Flathub has [new app metadata guidelines](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines), which this app is already in line with except for a few minor issues with the screenshots:

- Screenshots should not be taller than 700px (excluding shadow), because otherwise they are scaled down too much to be visible at thumbnail sizes in app stores. We recommend a 1000x700 px size for most apps. If you're concerned about showing off all of the list rows, you could include two screenshots at 700px height, one scrolled to the top and one to the bottom.
- Window controls should use the platform default settings (close button on the right in this case). The current screenshot has it on the left side.

This blog post has a bit more context on the curation initiative: https://docs.flathub.org/blog/quality-moderation

**Comment by Bytezz** [comment]
Thanks @bertob for reporting.
Lately I've been a bit of touch so I've missed these new guidelines.
Will comply as soon as I have time.

Anyway, I would like to point out that, since there are a LOT of different default configurations on a LOT of different distros, maybe windows' title buttons position should not concern that much. But I understand the motivation.

**Comment by bertob** [comment]
> Anyway, I would like to point out that, since there are a LOT of different default configurations on a LOT of different distros

That's why we specify that it's the `platform` default, rather than the distro. There are thousands of distros, but only a handful of app platforms (GNOME, KDE, elementary), and unlike with distros there is a single clear default there :)

**Comment by Bytezz** [comment]
> That's why we specify that it's the `platform` default, rather than the distro.
Ok, that makes sense.

Going back to screenshots, are half dark/light theme screenshots ok?
![iplookup-1](https://github.com/Bytezz/IPLookup-gtk/assets/25850701/e3f00e42-d583-4b2a-89da-3b01e4df5c07)

**Comment by bertob** [comment]
No, screenshots should be not be edited. You can include one or two extra screenshots in dark to show that it's supported, but otherwise just use the default (light).

By the way, your example here is a bit too small, I'd try to go as close to 1000x700 as possible (maybe a bit narrower in this case since it's just a single list, e.g. 700x700 or so?).

**Comment by Bytezz** [comment]
Sorry for late response (I'm on vacation).
What about these?
![Screenshot from 2024-02-10 17-53-22](https://github.com/Bytezz/IPLookup-gtk/assets/25850701/dca3146c-83ad-49cf-aade-b576d426ae47)
![Screenshot from 2024-02-10 17-53-31](https://github.com/Bytezz/IPLookup-gtk/assets/25850701/80f3d9d7-86cc-4571-bb2d-6720f207fd63)

These are very close to 700x700px (698x605px with shadows)

**Comment by bertob** [comment]
Would be even better without visible sidebars, but looks great otherwise!

**Comment by Bytezz** [comment]
Closed by commit `c92e86f5f65c0b0f12dc5891889f7b796ed4b422`

**Comment by Bytezz** [comment]
Closed by `c92e86f5f65c0b0f12dc5891889f7b796ed4b422`

**Comment by bertob** [comment]
Just realized that the window controls are non-default (close button should be on the right), sorry for not catching this earlier :disappointed:

**Comment by Bytezz** [comment]
Don't worry, I've noticed it as soon as I pushed the commit.
Force pushed amended commit right after.
