### ISSUE TITLE
Inconsistent IPv6 lookups?

### ISSUE THREAD

**Issue by nekohayo** [Bytezz/IPLookup-gtk#32]
The app is able to get my own public IPv6 from the "Get Your IP" menu action, but if I ask to look up some server on the Internet where I would expect IPv6 like `google.com`, `lafibre.info`, `microsoft.com`, oftentimes I only get an IPv4 result. Interestingly, if I ask it to lookup `microsoft.com` (or `google.com`), then I get different results on each try:

https://github.com/user-attachments/assets/1860bd3b-713f-417e-8d67-2bf4c3a71dbd

Shouldn't it be returning both IPv4 and IPv6 (when available) everytime?

**Comment by Bytezz** [comment]
Hostname to IP is made by the same API the software uses to get IP infos (http://ip-api.com/json/microsoft.com (use http, not https)).
What I can do is resolving hostname locally and asking those API infos about resolved IP which would be (hopefully) the same on every request (given all of them are made in the same region).
By doing this the software could check whether an ipv6 (other than ipv4) is available for a given hostname.

Thanks for the report.

**Comment by Bytezz** [comment]
Using `socket` lib in Python3, microsoft.com resolves to multiple IPs.  
How do you prefer this data to be shown?  
By showing all of them in a list? Or by just showing the first IPv4 and IPv6 (if there is one), but the first IP could be different on every resolve.

```python
>>> import socket
>>> for i in socket.getaddrinfo("microsoft.com", None):
...  print(i[4][0])
... 
20.231.239.246
20.231.239.246
20.231.239.246
20.70.246.20
20.70.246.20
20.70.246.20
20.236.44.162
20.236.44.162
20.236.44.162
20.112.250.133
20.112.250.133
20.112.250.133
20.76.201.171
20.76.201.171
20.76.201.171
2603:1020:201:10::10f
2603:1020:201:10::10f
2603:1020:201:10::10f
2603:1030:20e:3::23c
2603:1030:20e:3::23c
2603:1030:20e:3::23c
2603:1010:3:3::5b
2603:1010:3:3::5b
2603:1010:3:3::5b
2603:1030:c02:8::14
2603:1030:c02:8::14
2603:1030:c02:8::14
2603:1030:b:3::152
2603:1030:b:3::152
2603:1030:b:3::152
```

**Comment by nekohayo** [comment]
Maybe it could show an expandable row widget (a bit like GNOME Calendar's current date/time in the event editor dialog) that shows a summary when not expanded, i.e. "15 IPv4 + 15 IPv6 found 🞃" ?

**Comment by nekohayo** [comment]
To save vertical space, it could also display the IPv4 and IPv6 strings on two columns within the same expandable row widget, that way it's less of a vertical scrollfest, and I bet it would still work even on narrow screens…

**Comment by Bytezz** [comment]
Dunno what widget to use to list all of them following HIG :/

![Screenshot](https://github.com/user-attachments/assets/d114af77-6ebe-4159-bb86-c69f827ff530)

**Comment by Bytezz** [comment]
![image](https://github.com/user-attachments/assets/fec7c8b0-6fd0-4b3e-8dc2-942771d475b5)
