### ISSUE TITLE
Fullcolor App Icon

### ISSUE THREAD

**Issue by jimmac** [Bytezz/IPLookup-gtk#9]
IP Lookup is a neat app, it should have a nice visual identity rather than a symbolic globe. I'm interested in helping out with some design work.

**Comment by Bytezz** [comment]
Hi, thanks for your work. Really impressive, they are beautiful.
I especially like the last one because it's a full size circle, got "IP" (so it's easier to understand whats the app does by just looking at the icon) and I really like the "navigation" map.

**Comment by jimmac** [comment]
It's generally considered a flaw to use text in iconography, but I think we can make an exception here. An alternative would be to hint at an IP address:

![1.1.1.1](https://github.com/Bytezz/IPLookup-gtk/assets/14821/34deea7f-8a47-4227-82b4-d1e3034a9b57)

But the balance seems in favor of the original idea:

![IP](https://github.com/Bytezz/IPLookup-gtk/assets/14821/79e41a47-df8f-425e-8d89-554a9cee8c62)

**Comment by Bytezz** [comment]
> It's generally considered a flaw to use text in iconography
Since IP does not have an icon and is a very short international word, I think it would be acceptable to use the word itself as an icon to identify it.  

> An alternative would be to hint at an IP address
Perhaps that would be less intuitive and even more text would be added.
